### ISSUE TITLE
The Wire.requestFrom() does not need Wire.beginTransmission() or Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [RABlibs/ITG3200_library#1]
The Wire.beginTransmission() and Wire.endTransmission() are only used when writing data.

The Wire.requestFrom() is a complete I2C transaction on its own.

In the file "ITG3200.cpp", in the function "readmem()", you can remove the Wire.beginTransmission() and Wire.endTransmission() that are around the Wire.requestFrom().

**Comment by Fibird** [comment]
Got it! Thanks for your correction.
